name: Auto-label issues
on:
  issues:
    types: [opened]

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Apply labels
        uses: actions/github-script@v7
        with:
          script: |
            const { data } = await github.rest.issues.listLabelsForRepo({
              ...context.repo,
              per_page: 100,
            });
            const existingLabels = new Set(data.map((l) => l.name));
            const labels = (
              context.payload.issue.body.split(/### Affected Helm charts/)[1] || ""
            )
              .trim()
              .split(",")
              .map((s) => s.trim())
              .filter((s) => s && existingLabels.has(s));
            if (labels.length) {
              await github.rest.issues.addLabels({
                ...context.repo,
                issue_number: context.issue.number,
                labels,
              });
            }
